#!/bin/bash
# PulseKart Hybrid Deployment Script
# Vercel (Frontend) + Render (Backend + Database)
# Usage: ./deploy-hybrid.sh

set -e  # Exit on error

echo "🚀 PulseKart Hybrid Deployment"
echo "================================"
echo ""

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Check prerequisites
echo "📋 Checking prerequisites..."

# Check Node
if ! command -v node &> /dev/null; then
    echo "${RED}✗ Node.js not installed${NC}"
    echo "Install from: https://nodejs.org"
    exit 1
fi
echo "${GREEN}✓ Node.js installed${NC}"

# Check Git
if ! command -v git &> /dev/null; then
    echo "${RED}✗ Git not installed${NC}"
    exit 1
fi
echo "${GREEN}✓ Git installed${NC}"

# Check Vercel CLI
if ! command -v vercel &> /dev/null; then
    echo "${YELLOW}⚠ Vercel CLI not found, installing...${NC}"
    npm i -g vercel
fi
echo "${GREEN}✓ Vercel CLI ready${NC}"

# Generate JWT Secret
JWT_SECRET=$(openssl rand -base64 32)
echo "${GREEN}✓ Generated JWT_SECRET${NC}"

echo ""
echo "================================"
echo ""

# Step 1: Build Check
echo "🔨 Step 1: Building project..."
echo "${BLUE}Building frontend...${NC}"
npm run build > /dev/null 2>&1 && echo "${GREEN}✓ Frontend build successful${NC}" || echo "${YELLOW}⚠ Frontend build issues (will fix on deploy)${NC}"

echo "${BLUE}Building backend...${NC}"
cd backend
npm run build > /dev/null 2>&1 && echo "${GREEN}✓ Backend build successful${NC}" || echo "${YELLOW}⚠ Backend build issues (will fix on deploy)${NC}"
cd ..

echo ""
echo "================================"
echo ""

# Step 2: Prepare Environment Files
echo "📝 Step 2: Preparing environment files..."

# Frontend .env.local
cat > .env.local << EOF
NEXT_PUBLIC_API_URL=https://pulsekart-api.onrender.com
EOF
echo "${GREEN}✓ Created .env.local${NC}"

# Backend .env for Render
cat > backend/.env.render << EOF
# Auto-generated by deploy script
NODE_ENV=production
PORT=10000
JWT_SECRET=${JWT_SECRET}
POSTGRES_HOST=\${POSTGRES_HOST}
POSTGRES_PORT=5432
POSTGRES_USER=\${POSTGRES_USER}
POSTGRES_PASSWORD=\${POSTGRES_PASSWORD}
POSTGRES_DB=\${POSTGRES_DB}
CORS_ORIGINS=https://pulsekart.vercel.app
EOF
echo "${GREEN}✓ Created backend/.env.render${NC}"

echo ""
echo "================================"
echo ""

# Step 3: Git Check
echo "📦 Step 3: Git preparation..."

if [ -n "$(git status --porcelain)" ]; then
    echo "${YELLOW}⚠ Uncommitted changes detected${NC}"
    read -p "Commit changes? (y/n): " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        git add -A
        git commit -m "chore: prepare for deployment [auto]"
        echo "${GREEN}✓ Changes committed${NC}"
    fi
else
    echo "${GREEN}✓ Working directory clean${NC}"
fi

# Push to GitHub
echo "${BLUE}Pushing to GitHub...${NC}"
git push origin $(git branch --show-current)
echo "${GREEN}✓ Pushed to GitHub${NC}"

echo ""
echo "================================"
echo ""

# Step 4: Deploy Instructions
echo "🚀 Step 4: Deployment Instructions"
echo ""
echo "${GREEN}✅ Pre-deployment complete!${NC}"
echo ""
echo "${YELLOW}Now complete these steps:${NC}"
echo ""

echo "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo "1️⃣  DEPLOY BACKEND + DATABASE (Render)"
echo "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "   URL: https://dashboard.render.com/blueprint"
echo ""
echo "   Steps:"
echo "   • Click 'New Blueprint'"
echo "   • Select: ak1458/PulseKart-Nextjs-web-app"
echo "   • Branch: $(git branch --show-current)"
echo "   • Click 'Apply'"
echo "   • Wait 5-10 minutes"
echo ""
echo "   Render will create:"
echo "   • PostgreSQL database"
echo "   • Backend API server"
echo ""

echo "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo "2️⃣  GET BACKEND URL"
echo "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "   After Render deploys:"
echo "   • Go to: https://dashboard.render.com"
echo "   • Click your backend service"
echo "   • Copy the URL (e.g., https://pulsekart-api.onrender.com)"
echo ""

echo "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo "3️⃣  UPDATE FRONTEND ENV"
echo "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "   Update .env.local with your backend URL:"
echo "   NEXT_PUBLIC_API_URL=https://YOUR-BACKEND-URL.onrender.com"
echo ""

echo "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo "4️⃣  DEPLOY FRONTEND (Vercel)"
echo "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "   Run this command:"
echo "   ${GREEN}vercel --prod${NC}"
echo ""
echo "   Or go to: https://vercel.com/new"
echo "   • Import GitHub repo"
echo "   • Framework: Next.js"
echo "   • Add env var: NEXT_PUBLIC_API_URL"
echo "   • Deploy"
echo ""

echo "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo "5️⃣  UPDATE CORS"
echo "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "   In Render dashboard:"
echo "   • Go to backend service"
echo "   • Environment → Edit"
echo "   • Update CORS_ORIGINS with your Vercel URL"
echo "   • Example: CORS_ORIGINS=https://pulsekart.vercel.app"
echo ""

echo "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo "✅ DONE!"
echo "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "Your app will be at:"
echo "${GREEN}Frontend:${NC} https://pulsekart.vercel.app"
echo "${GREEN}Backend:${NC}  https://pulsekart-api.onrender.com"
echo ""
echo "${YELLOW}Total time: ~15 minutes${NC}"
echo "${YELLOW}Total cost: $0 (free tier)${NC}"
echo ""

# Save deployment info
cat > DEPLOY_INFO.txt << EOF
PulseKart Deployment Info
Generated: $(date)

JWT_SECRET: ${JWT_SECRET}
Git Branch: $(git branch --show-current)
Git Commit: $(git rev-parse --short HEAD)

Steps Completed:
✓ Environment files created
✓ Git pushed to GitHub
✓ Build verified

Next Steps:
1. Deploy backend on Render (blueprint)
2. Get backend URL
3. Deploy frontend on Vercel
4. Update CORS

IMPORTANT: Save this file securely!
EOF

echo "${GREEN}✓ Deployment info saved to DEPLOY_INFO.txt${NC}"
echo ""
